language: python

matrix:
  include:

    # Set the python version to 3.7.4
    - python: 3.7.4
      dist: xenial
      #env: NUMPY=1.9 SCIPY=0.15

before_install:

  # Install Miniconda.

  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  #- conda update --prefix /home/travis/miniconda2 anaconda --yes

install:

  # We just set up a conda environment with the right Python version.
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test

  # Below, include the dependencies you want to install with conda, optionally
  # specifying versions used in the matrix above. If you split this into
  # multiple conda install commands, you should always include numpy=$NUMPY as
  # the first package to install (for every conda install command) otherwise
  # numpy may be automatically upgraded.

  - conda test update -f environment.yml
  - conda install --yes pytest

  # You can also install some dependencies with pip if not available in conda

  # - pip install ...

script:

  - py.test  # will run all tests in the package