language: python

matrix:
  include:

    # Set the python version to 3.7.4
    - python: 3.7.4
      dist: xenial

    # Set the python version to 3.7.4
    #- python: 3.7.4
    #  os: osx

before_install:

  # Install Miniconda.
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH

  # Update conda (otherwise conda can't be found)
  - conda update conda --yes

  # Set up a conda environment with the right Python version.
  - conda create --yes --name travis_env python=$TRAVIS_PYTHON_VERSION
  - source activate travis_env

install:
  # Install the requirements from the environment file
  # - conda install -c schrodinger pymol -y
  # Required...
  - git clone https://github.com/xchem/gemmi_pandda.git
  - cd ./gemmi_pandda
  - pip install --force-reinstall .
  - cd ..
  # Also Required
  - git clone https://github.com/xchem/pandda_gemmi.git
  - cd ./pandda_gemmi
  - pip install -e .
  - cd ..
  - conda install -c rdkit rdkit -y
  # Install additional dependencies used only for travis / testing
  - conda install --yes pytest codecov
  # You can also install some dependencies with pip if not available in conda
  - pip install -e .

script:
  - coverage run -m py.test # will run all tests in the package
  - coverage report --omit="pandda_gemmi/*,gemmi_pandda/*,tests/*" -m  # Nicely shows a report of coverage of each script
  #- coverage run -m unittest discover

after_success:
  - codecov # Push the results back to codecov (code coverage) for nicer visualization
