# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7.4
matrix:
  include:
    - python: 3.7.4
      dist: xenial

# Install the requirements and codecov pip dependency
install:
  - pip install -r requirements1.txt
  - pip install codecov

# Run the unit test
script:
  - python test/xcimporter/test_validate.py
  - coverage run test/xcimporter/test_validate.py

# Push the results back to codecov
after_success:
  - codecov
