name: fragalysis_env
channels:
  - rdkit
  - schrodinger
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - apbs=1.5
  - asn1crypto=1.2.0
  - biopython=1.74
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.27
  - cairo=1.14.12
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.8
  - dbus=1.13.12
  - expat=2.2.6
  - flask=1.1.1
  - fontconfig=2.13.0
  - freemol=1.158
  - freetype=2.9.1
  - glew=2.0.0
  - glib=2.63.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.4
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - jpeg=9b
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - mengine=1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mpeg_encode=1
  - mtz2ccp4_px=1.0
  - ncurses=6.1
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - pcre=8.43
  - pdb2pqr=2.1.1
  - pillow=6.2.1
  - pip:
      - pypdb=1.300
  - pixman=0.38.0
  - pmw=2.0.1
  - py-boost=1.67.0
  - pycparser=2.19
  - pymol=2.3.4
  - pyopenssl=19.1.0
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - pytz=2019.3
  - qt=5.9.7
  - rdkit=2019.09.2.0
  - readline=7.0
  - requests=2.22.0
  - rigimol=1.3
  - setuptools=42.0.2
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - urllib3=1.25.7
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

